### ISSUE TITLE
能否考虑加入dataX导入数据自动建表功能

### ISSUE THREAD

**Issue by weihebu** [wgzhao/DataX#101]
Mysql到Mysql导入自动建表参考：
https://www.jianshu.com/p/e2f1d781895f
这个功能最好可以扩展到常见的关系型数据库。

**Comment by weihebu** [comment]
另外这边issue选不了类型，只有bug类型。

**Comment by wgzhao** [comment]
这个功能不再DataX上实现，我正在做基于DataX的任务管理与调度系统，其中任意关系性数据库之间，任意关系性写入非关系性数据库均可以实现自动建表，同时还涵盖其他功能。

开发这个工具的目的也是目前我们自己业务上的需要，当前我们内部通过多个小工具的协同实现了自动建表、字段自动演进（增加字段，字段类型变更，减少字段），自动任务依赖解析与调度等。我们计划把其综合成一个系统。

**Comment by weihebu** [comment]
有什么小工具推荐嘛，是开源的、收费的还是自研的？

**Comment by wgzhao** [comment]
自研的，目前实现的和当前环境有较深度绑定，并不算通用。

**Comment by feibaliang** [comment]
> 这个功能不再DataX上实现，我正在做基于DataX的任务管理与调度系统，其中任意关系性数据库之间，任意关系性写入非关系性数据库均可以实现自动建表，同时还涵盖其他功能。
> 
> 开发这个工具的目的也是目前我们自己业务上的需要，当前我们内部通过多个小工具的协同实现了自动建表、字段自动演进（增加字段，字段类型变更，减少字段），自动任务依赖解析与调度等。我们计划把其综合成一个系统。
这个有开源计划吗

**Comment by feibaliang** [comment]
> 这个功能不再DataX上实现，我正在做基于DataX的任务管理与调度系统，其中任意关系性数据库之间，任意关系性写入非关系性数据库均可以实现自动建表，同时还涵盖其他功能。
> 
> 开发这个工具的目的也是目前我们自己业务上的需要，当前我们内部通过多个小工具的协同实现了自动建表、字段自动演进（增加字段，字段类型变更，减少字段），自动任务依赖解析与调度等。我们计划把其综合成一个系统。

这个有开源计划吗

**Comment by hhw3KevinHou** [comment]
中国的开源基本就烂尾，好东西都不开源。

> > 这个功能不再DataX上实现，我正在做基于DataX的任务管理与调度系统，其中任意关系性数据库之间，任意关系性写入非关系性数据库均可以实现自动建表，同时还涵盖其他功能。
> > 开发这个工具的目的也是目前我们自己业务上的需要，当前我们内部通过多个小工具的协同实现了自动建表、字段自动演进（增加字段，字段类型变更，减少字段），自动任务依赖解析与调度等。我们计划把其综合成一个系统。
> 
> 这个有开源计划吗

中国的开源基本就烂尾，好东西都不开源。
