### ISSUE TITLE
datax读取数据时增加自定义字段跟值

### ISSUE THREAD

**Issue by weihebu** [wgzhao/DataX#102]
希望可以增加一个功能，就是datax读取数据时，增加自定义字段跟值。比如说源表没有send_date这个字段，但是目标表有这个字段。我可以手动添加这个字段，并且写上一个值传入过去。

**Comment by wgzhao** [comment]
这个功能已经实现了，请参考[这里](https://datax.readthedocs.io/zh_CN/latest/reader/rdbmsreader.html#column)

**Comment by weihebu** [comment]
你好，关于项目首页下方的冒烟测试，测试完整命令应该是 python bin/datax.py job/job.json吧？我看文档里就只写了bin/datax.py job/job.json。
