### ISSUE TITLE
是否支持定时任务!

### ISSUE THREAD

**Issue by hzl0316** [wgzhao/DataX#113]
这个版本是否支持定时抽取

**Comment by wgzhao** [comment]
这是一个ETL工具，不是一个调度工具，所以并不支持定时抽取

**Comment by glxfeng** [comment]
> 这个版本是否支持定时抽取

有个项目叫web-datax你可以看看，里面集成了个调度工具

**Comment by wgzhao** [comment]
> > 这个版本是否支持定时抽取
> 
> 有个项目叫web-datax你可以看看，里面集成了个调度工具

这个项目我知道，不过目前DataX这个项目主要是解决ETL的问题，至于调度，会是另外一个单独的项目，请参见 #101 的讨论

**Comment by glxfeng** [comment]
> > > 这个版本是否支持定时抽取
> > 
> > 
> > 有个项目叫web-datax你可以看看，里面集成了个调度工具
> 
> 这个项目我知道，不过目前DataX这个项目主要是解决ETL的问题，至于调度，会是另外一个单独的项目，请参见 #101 的讨论

嗯，我只是给楼主个建议，我自己用的自动建表也是自研的，调度用的dolphinschedule

**Comment by wgzhao** [comment]
感谢反馈
