### ISSUE TITLE
看看是否有方法攻克ElasticSearch Reader

### ISSUE THREAD

**Issue by cmdares** [wgzhao/DataX#118]
比如让SQL中写DSL，或者要求ES6.3之上也行，或者集成插件也行。
目前的需求是将ES中的增量信息，定时同步到clickhouse，当前的解决办法是定时触发logstash导出csv，clickhouse 导入csv，相对繁琐。希望能够通过datax框架完成这一任务。
感谢！

**Comment by wgzhao** [comment]
@cmdares 感谢您的提议，我会认真考虑如何实现

**Comment by wgzhao** [comment]
@cmdares 已经支持 Elasticsearch 数据读取

**Comment by cmdares** [comment]
这么快！先赞再说！
注意下大数据量下的获取上限和游标问题。需要做个海量数据测试下稳定性。
同时还需要注意ES多种安全认证的模式支撑。

**Comment by wgzhao** [comment]
1. 安全认证目前仅支持最简单的帐号密码方式
2. 目前仅数据获取测试通过，并没有做海量数据下的严格测试
3. 欢迎进行测试并提交issue
