### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by rogerlzp** [wgzhao/DataX#12]
Hi 
I failed with the error:

DataX (DATAX-V3), From Alibaba !
Copyright (C) 2010-2017, Alibaba Group. All Rights Reserved.

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

any tip to fix this?

**Comment by wgzhao** [comment]
@rogerlzp  thank for you report

I found it's cause is slf4j is not compliant logback-class in some version, I fixed it
