### ISSUE TITLE
异构数据源头和目标传递复杂数据类型

### ISSUE THREAD

**Issue by cmdares** [wgzhao/DataX#122]
如题：针对复杂数据类型，如：数组、嵌套、Map、Json、GeoPoint等复杂类型的抽取-转换-写入。
对于已经适配的这些类数据源支持的怎么样，是否考虑把这块内容仔细梳理并完善一下。
感谢。

**Comment by wgzhao** [comment]
@cmdares 请看每个插件的文档中的数据类型支持，对能够支持的已经做了说明
