### ISSUE TITLE
3.2.1编译之后怎么插件少了

### ISSUE THREAD

**Issue by glxfeng** [wgzhao/DataX#123]
这是3.2.1编译完的插件
![image](https://user-images.githubusercontent.com/57620584/108588567-d91f6700-7394-11eb-87c7-52cc646e65f1.png)
这是3.1.9编译完的插件
![image](https://user-images.githubusercontent.com/57620584/108588716-97db8700-7395-11eb-96da-ca08d2988169.png)
mysqlreader怎么没了

**Comment by glxfeng** [comment]
我把3.1.9编译好的mysqlreader复制过来也不行，报错

**Comment by wgzhao** [comment]
你尝试使用 `mvn package -pl :mysqlreader` 编译试试

**Comment by glxfeng** [comment]
> 你尝试使用 `mvn package -pl :mysqlreader` 编译试试

这样编译出来的没问题

**Comment by wgzhao** [comment]
下个版本将会修复该问题

**Comment by john5480** [comment]
3.2.2似乎没有elasticsearchreader模块，不管是源码编译还是发布包。
源码编译日志显示已经编译，但target目录找不到elasticsearchreader文件夹，其他的都有

**Comment by wgzhao** [comment]
> 3.2.2似乎没有elasticsearchreader模块，不管是源码编译还是发布包。
> 源码编译日志显示已经编译，但target目录找不到elasticsearchreader文件夹，其他的都有

查看 `package.xml` 文件，的确少了  `elasticsearchreader` 的打包。
看来需要对 `package.xml` 文件做些改动了
