### ISSUE TITLE
InfluxDBWriter 未实现tag 设置选项 

### ISSUE THREAD

**Issue by covered** [wgzhao/DataX#125]
InfluxDBWriter 未实现tag 设置选项  ，期待实现 #

感谢你的项目！

**Comment by covered** [comment]
`                Point.Builder builder = Point.measurement(table);
                Map<String, Object> fields = new HashMap<>();
                // tags
                //Map<String, String> tags = new HashMap<String, String>();
                // 第一个字符必须是时间戳类型
                builder.time(record.getColumn(0).asLong(), TimeUnit.MILLISECONDS);
                for (int i=1; i< columnNumber; i++) {
                    String name = this.columns.get(i).getString("name");
                    String type = this.columns.get(i).getString("type").toUpperCase();
                    Column column = record.getColumn(i);
                    switch (type) {
                        case "INT":
                        case "LONG":
                            fields.put(name, column.asLong());
                            break;
                        case "DATE":
                            fields.put(name, column.asDate());
                            break;
                        case "DOUBLE":
                            fields.put(name, column.asDouble());
                            break;
                        case "DECIMAL":
                            fields.put(name, column.asBigDecimal());
                            break;
                        case "BINARY":
                            fields.put(name, column.asBytes());
                            break;
                        //tags
                        //case "TAGS":
                        //    tags.put(name, column.asString());
                        //    break;
                        default:
                            fields.put(name, column.asString());
                            break;
                    }
                }
                //tags
                //builder.tag(tags);
                builder.fields(fields);
                influxDB.write(database, rp, builder.build());
            }
        }`

**Comment by wgzhao** [comment]
感谢反馈，我进行测试后加入

**Comment by wgzhao** [comment]
@covered 从当前代码来看

```java
  case "BINARY":
      fields.put(name, column.asBytes());
      break;
  default:
      fields.put(name, column.asString());
      break;
```
如果你设置了type为tag，插件不会报错，而是会用字符串形式写入到字段中，间接达到了你想要的结果
