### ISSUE TITLE
关于HDFSReader的一些疑问

### ISSUE THREAD

**Issue by Wang-idea** [wgzhao/DataX#134]
想问一下，原本关于HdfsReader的线程数量，通过通道数指定无效，是根据文件数量决定的，这个问题
您的DataX有解决该问题吗 

速度控制并没有起效，想知道您的DataX有这个问题吗

标签打成bug 不好意思 因为第一次使用github提出issue 不知道在哪里修改

**Comment by wgzhao** [comment]
感谢您的反馈

> 通过通道数指定无效，是根据文件数量决定的

目前依然是根据文件数量而不是channel配置来分配线程数的，不根据channel数进行分配涉及到的因素很多，比如假定channel比文件数量大，则涉及到文件切分的问题，而文件是否可切分又涉及到存储格式和压缩算法的问题。所以用文件数量作为线程数是一个简单也高效的做法，实际上很多读取HDFS文件的程序的线程数量都是依据这个原则来做的。

> 速度控制并没有起效

这个不太清楚具体是指哪个方面，方便举个例子具体说明下吗？

**Comment by Wang-idea** [comment]
非常感谢您的回复
主要是json文件中这块
"setting":{
"speed":{
	"byte":3145728,
	"channel":3,
	"record":3000
}
这部分设置的Record记录数或者byte数 好像并没有起作用？
还请您指导

**Comment by wgzhao** [comment]
> 非常感谢您的回复
> 主要是json文件中这块
> "setting":{
> "speed":{
> "byte":3145728,
> "channel":3,
> "record":3000
> }
> 这部分设置的Record记录数或者byte数 好像并没有起作用？
> 还请您指导

这部分的限制还需要和 `conf/core.json` 中的  `transport.channel.speed` 配置项相结合，但我发现似乎只与 `core.json` 中的配置有关，更详细的，还需要去进一步梳理源代码，这部分代码我还没有仔细阅读过，基本上也没有改动。
