### ISSUE TITLE
DorisWriter加transformer后导入不成功

### ISSUE THREAD

**Issue by mklzl** [wgzhao/DataX#139]
如题，不增加transformer时能够正确导入，增加后，导入不报错，但是Doris没数据，且startWriter方法内打印的消息也没有打印

**Comment by wgzhao** [comment]
@mklzl 感谢您的反馈，如果方便，还请您给出具体的执行过程，比如使用的配置文件（json文件），执行过程的日志，以及执行的环境等。

**Comment by wgzhao** [comment]
No further more detailed information, close this issue
