### ISSUE TITLE
关于使用中速度突然为0的问题,主要在oracle->hdfs遇到

### ISSUE THREAD

**Issue by jasonmba** [wgzhao/DataX#145]
现在主要出现2种情况，一种是突然一个子任务中间出现connection reset，然后到最后会卡在最后一个子任务。
另一种是没有任何错误征兆，就是突然的卡死,waitreadtime也是呈现卡住不动的状态
![image](https://user-images.githubusercontent.com/22310870/110722571-7c092980-824d-11eb-89f1-f706682fd872.png)

我在datax官方issue看到一个关掉的,说可能是
这种情况经常出现在hdfswriter的task.init()， hdfsHelper.getFileSystem(defaultFS, writerSliceConfig); 这里初始化卡住了
测试重现的方法：在Writer.Task.init() 或者 prepare()
try {
Thread.sleep(3000);
} catch (InterruptedException e) {
e.printStackTrace();
}
会导致reader 结束，从而导致程序出现严重bug
但是这个大概率应该不是我遇到的问题

**Comment by wgzhao** [comment]
我这边遇到过类似你这样的问题，不过是反过来，`hdfs->oracle`，排查了很久，后来发现是Oracle那边的限制。
你这种情况，建议出现速度为0的情况下，看看Oracle那边的连接情况，是否受限了。
