### ISSUE TITLE
influxdb batch size、query use chunk size

### ISSUE THREAD

**Issue by IronsDu** [wgzhao/DataX#150]
**Describe the bug**
你好，我遇到一个BUG和一个建议。
1. 在写入influxdb的配置中，如果batch size大于实际reader提供的数据条数，则最终数据并没有写入到influxdb。修复方式：在https://github.com/wgzhao/DataX/blob/e99f3f634a191a4623889cc793217adec8964209/plugin/writer/influxdbwriter/src/main/java/com/wgzhao/datax/plugin/writer/influxdbwriter/InfluxDBWriterTask.java#L131 for循环语句外面（后面）添加如下代码进行写入：
```go
if (influxDB.isBatchEnabled()) {
                influxDB.flush();
}
``` 
2. 建议读取数据时是否采用chunk传输？比如在 https://github.com/wgzhao/DataX/blob/e99f3f634a191a4623889cc793217adec8964209/plugin/reader/influxdbreader/src/main/java/com/wgzhao/datax/plugin/reader/influxdbreader/InfluxDBReaderTask.java#L106 里调用chunk版的query。
**To Reproduce**
1. paste  json content of running job
2. paste the output of running job

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. CentOS]
 - JDK Version [e.g. 1.8]
 - DataX Version [e.g. 3.1.3]

**Additional context**

**Comment by wgzhao** [comment]
感谢反馈，我将在下个版本修复这个问题

**Comment by IronsDu** [comment]
此外，是否可以在Job/Task的destory里调用influxdb.Close释放客户端资源？

**Comment by wgzhao** [comment]
>建议读取数据时是否采用chunk传输？

influxdb 读取插件不再使用 `influxdb-java`  包，参见 #146 ，下个版本会发布

**Comment by lysShub** [comment]
> 个版本修复这个问题

influxdb Java sdk是支持chunk的，https://github.com/influxdata/influxdb-java/issues/465
