### ISSUE TITLE
新版本连接sqlserver报错

### ISSUE THREAD

**Issue by ProjectMoss** [wgzhao/DataX#155]
拉取得源码编译3.2.4连接sqlserver会抛出异常。3.2.3没有这个问题。
具体异常如下图

![20210325100930](https://user-images.githubusercontent.com/57606473/112408542-f27c5000-8d52-11eb-8930-80b6a7920af3.png)

**Comment by wgzhao** [comment]
从报错看是JDBC驱动的java版本不对，其版本是JDK15，我们编译使用的是JDK8，我马上替换pom中的驱动版本

**Comment by wgzhao** [comment]
临时解决版本是下载 [mssql-jdbc-9.2.1.jre8.jar](https://search.maven.org/remotecontent?filepath=com/microsoft/sqlserver/mssql-jdbc/9.2.1.jre8/mssql-jdbc-9.2.1.jre8.jar) 替换插件里的 `mssql-jdbc-9.2.1.jre15.jar` 文件

**Comment by ProjectMoss** [comment]
好的，多谢
