### ISSUE TITLE
Could not find or load main class com.wgzhao.datax.core.Engine

### ISSUE THREAD

**Issue by mosynaq** [wgzhao/DataX#158]
![Screenshot 2021-04-04 175113](https://user-images.githubusercontent.com/7660183/113510101-3864bf80-956e-11eb-9e57-c06bf8e21bee.png)

**Comment by MrPoint1400** [comment]
C:\ETL\DataX_ETL\target\datax\datax-3.2.3>python bin/datax.py job/job.json
Error: Could not find or load main class com.wgzhao.datax.core.Engine

**Comment by wgzhao** [comment]
@mosynaq thanks for your feedback. Currently, datax is not good enough for windows compatibility, I am improving this, hopefully in the next version can be better compatible with windows system

**Comment by wgzhao** [comment]
you can download the [datax.py.zip](https://github.com/wgzhao/DataX/files/6262217/datax.py.zip)  and uncompress your `DATAX_HOME\bin` folder, replace the current `datax.py`, It should work.
