### ISSUE TITLE
clickhouse reader下载下来后解压。报NoClassDefFoundError

### ISSUE THREAD

**Issue by suyj0109** [wgzhao/DataX#164]
是我安装插件的方式不对吗，还是路径有问题。谢谢作者了，急

**Comment by wgzhao** [comment]
感谢你的反馈
能够详细说明你的操作步骤并给出报错的详细内容
这样才能更快的帮您解决问题

**Comment by suyj0109** [comment]
我把下载下来的clickhousereader.zip解压至/usr/local/datax/datax/plugin/reader。重启datax web 构建任务。
![image](https://user-images.githubusercontent.com/30523996/115482239-c6d08500-a280-11eb-9b6b-59a241c14328.png)
 报如下图的错

**Comment by suyj0109** [comment]
![Uploading image.png…]()

**Comment by suyj0109** [comment]
![image](https://user-images.githubusercontent.com/30523996/115482860-32ffb880-a282-11eb-8e90-02999a11ac24.png)

**Comment by wgzhao** [comment]
从日志截图来看，您的环境至少存在几个问题：
1. 核心版本应该不是我这里下载或者从目前代码仓库编译的，因为这边仓库没有`0.0.1-SNAPSHOT`版本
2. 插件和核心版本的包名不同，我的包命名空间是`com.wgzhao.datax`，您这边的核心包命名空间为 `com.alibaba.datax`
3. 从日志来看，`AnalysisStaticis` 这个包不知道从哪里来的，我这里没有。

建议您从仓库的[README](https://github.com/wgzhao/DataX/blob/master/README.md) 中提到的下载链接中下载完整包，然后进行测试。

感谢您的反馈。
