### ISSUE TITLE
同步presto ----> sqlserver报错

### ISSUE THREAD

**Issue by WangSleep** [wgzhao/DataX#174]
error_info：Exception in thread "job-0" java.lang.UnsupportedClassVersionError: com/microsoft/sqlserver/jdbc/SQLServerDriver has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 52.0

服务器java_version：1.8
datax_version：3.2.3

请问下该怎么修复么？
感激！！！

@wgzhao

**Comment by wgzhao** [comment]
SQL Server的驱动编译版本不对，你目前使用的驱动使用Java 11及以上版本编译的
而 DataX 目前使用 JDK8。

可以 从[https://search.maven.org/remotecontent?filepath=com/microsoft/sqlserver/mssql-jdbc/9.2.1.jre8/mssql-jdbc-9.2.1.jre8.jar](https://search.maven.org/remotecontent?filepath=com/microsoft/sqlserver/mssql-jdbc/9.2.1.jre8/mssql-jdbc-9.2.1.jre8.jar) 这里下载对应的驱动，然后替换目前插件中对应的JDBC驱动。

**Comment by WangSleep** [comment]
> SQL Server的驱动编译版本不对，你目前使用的驱动使用Java 11及以上版本编译的
> 而 DataX 目前使用 JDK8。
> 
> 可以 从https://search.maven.org/remotecontent?filepath=com/microsoft/sqlserver/mssql-jdbc/9.2.1.jre8/mssql-jdbc-9.2.1.jre8.jar 这里下载对应的驱动，然后替换目前插件中对应的JDBC驱动。


替换版本可以了。

非常感谢！！！
