### ISSUE TITLE
mysql 与 porsgresql 插件中的splitPk能否支持字符串型数据切分

### ISSUE THREAD

**Issue by weihebu** [wgzhao/DataX#178]
datax中的oracleReader插件中的splitPk支持整形、字符串型数据切分。但mysql 与 porsgresql 插件中的splitPk仅支持整形数据切分，我想问下这两个插件能否添加字符串型数据切分的功能？

**Comment by wgzhao** [comment]
MySQL 和 PostgreSQL 也是支持的

**Comment by weihebu** [comment]
那是从哪个版本开始起支持的呢？我之前下的2.1.2版本是不支持字符串的，阿里的datax也是不支持的。

**Comment by wgzhao** [comment]
`2.1.2` ？
我这里没有`2.x` 版本，最低版本是 `3.０.2`。从 `3.0.2` 就支持

**Comment by weihebu** [comment]
2.1.2是年初下的嘛，现在已经迭代上去了。
