### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4

### ISSUE THREAD

**Issue by JKwanghao** [wgzhao/DataX#179]
最新版本 3.2.4 clickhouse的writer的jar包有问题，3.1.9的jar包无问题

**Comment by wgzhao** [comment]
感谢反馈，能否给出详细的测试用例

**Comment by JKwanghao** [comment]
> 感谢反馈，能否给出详细的测试用例

这里用例很简单，就是通过mysql导入数据到clickhouse，使用的是你发布的datax-3.2.4，我切换回3.1.9，这个脚本执行就没问题，所以我觉得应该是 clickhouse插件jar包有点问题。因为测试，所以相应日志都清空了。  我感觉你的代码中是不是有for循环之类的，结果越界了？看这错误提示，感觉是for循环之类的，循环到了4，但是size为4，也就是index最多到3.

**Comment by wgzhao** [comment]
是在处理clickhouse的 `timestamp`, `datetime` 类型时，获取字段信息越界了，已经在当前 `master`  分支上修复
