### ISSUE TITLE
编译打包异常

### ISSUE THREAD

**Issue by ProjectMoss** [wgzhao/DataX#48]
编译会报错，这是什么原因啊
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single (release) on project datax-all: Failed to create assembly: Error creating assembly archive release: archive cannot be empty -> [Help 1]

**Comment by wgzhao** [comment]
因 assembly 配置文件我还在调整，所以打包需要按照两个步骤进行

```shell
mvn clean package
mvn package assembly:single
```

编译完成后，在 `target/datax`目录有 `datax-<version>` 文件夹，该文件夹即可使用

**Comment by ProjectMoss** [comment]
mvn clean package 编译打包还是会报错
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single (release) on project datax-all: Failed to create assembly: Error creating assembly archive release: archive cannot be empty -> [Help 1]

**Comment by wgzhao** [comment]
很抱歉，刚经过多轮测试，能够确认用以下方式临时解决打包问题。

1. 更新代码 `git pull`
2. 执行 `mvn clean install` 安装包到本地仓库
3. 执行**两次** `mvn package assembly:single` 生产目标文件夹，注意是执行两次。

也就是在本地执行以下命令:

```shell
git pull
mvn clean install
mvn package assembly:single
mvn package assembly:single
```

**Comment by ProjectMoss** [comment]
已解决
