### ISSUE TITLE
能提供编译包吗

### ISSUE THREAD

**Issue by ProjectMoss** [wgzhao/DataX#52]
好多包不架梯子根本拉不动，能直接提供个编译包就好了，放百度网盘啥的。

**Comment by wgzhao** [comment]
1.  使用国内的maven镜像就能下载所需的所有依赖包
2. 上传到国内网盘不知道能存放多久，有一定的风险
3. 好吧，我还是艰难的上传了一个，参考更新后的[README](https://github.com/wgzhao/DataX#不想编译)

**Comment by ProjectMoss** [comment]
谢谢大佬，已解决
