### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by ProjectMoss** [wgzhao/DataX#60]
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.726 s
[INFO] Finished at: 2020-11-17T15:54:12+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (run-sphinx) on project datax-docs: Command execution failed.: Process exited with an error: 127 (Exit value: 127) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :datax-docs

这个是什么原因啊

**Comment by wgzhao** [comment]
编译 `docs` 模块时，需要 `sphinx` 工具，改工具依赖Python以及对应的软件包。
如果你不需要文档，可以考虑使用下面的编译方式

`mvn clean package -pl !datax-docs`

或者修改项目根目录下的 `pom.xml`文件，删除

` <module>docs</module>`

一行后，再进行编译

**Comment by ProjectMoss** [comment]
pom.xml删除<module>docs</module>已解决问题。
