### ISSUE TITLE
反馈2个问题

### ISSUE THREAD

**Issue by ProjectMoss** [wgzhao/DataX#64]
1.在SqlServerReader能不能加上WITH(NOLOCK) ，在长时间读的时候防止触发查询锁；

2.在ClickHouseWriter能不能做写默认值的处理，一般clickhouse数据库建表的时候没有null，这样数值类型默认成0，字符串默认成空，日期类型默认成'1970-01-01'，时间类型默认'1970-01-01 08:00:00'等。

**Comment by wgzhao** [comment]
@ProjectMoss  感谢你的反馈

>1.在SqlServerReader能不能加上WITH(NOLOCK) ，在长时间读的时候防止触发查询锁

这个的确在设计和实现时没有考虑，不过从[官方文档](https://docs.microsoft.com/zh-cn/sql/t-sql/queries/hints-transact-sql-table?view=sql-server-ver15)介绍来看，`with(nolock)`等同于 设置事物隔离级别为 `READ UNCOMMITTED`，因此我们可以利用 `session` 这个配置参数，在job里，配置为 `SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED` 从而达到你说的目的。

>2.在ClickHouseWriter能不能做写默认值的处理，一般clickhouse数据库建表的时候没有null，这样数值类型默认成0，字符串默认成空，日期类型默认成'1970-01-01'，时间类型默认'1970-01-01 08:00:00'等

这个暂不考虑，因为 `DataX` 的目的是数据采集，采集意味着是需要“忠实”的把源数据写入到目标数据，除非在明确的做了数据转换工作，否则采集不应该自作主张的处理默认值。如果需要字段能填写目标值，可以考虑在建表时指定默认值。


再次感谢你的反馈。
