### ISSUE TITLE
能否添加oracle以及postgresql的Insert/Update功能

### ISSUE THREAD

**Issue by weihebu** [wgzhao/DataX#82]
oracle使用 merge into 语法实现。
postgresql采用 insert into ...on conflict语法实现。
附上博客：
https://blog.csdn.net/u013308496/article/details/106881907
https://blog.csdn.net/u013308496/article/details/106876691 以供参考。
但是他的修改不是很完美，破坏了原来insert的功能，后面只能配置update。
另外想要请教如何调试插件代码的，每个插件打包后引入再进行调试吗，这个不是很清楚，望指教。
目前我是参照这两篇博客：
https://www.jianshu.com/p/01672e5ea1b6  
https://blog.csdn.net/pharos/article/details/104147381 
把datax进行集成然后调试的，如有更好的调试办法，望告知，谢谢。

**Comment by wgzhao** [comment]
感谢你的反馈
1. Oracle 及 Postgresql 的合并插入功能开发我加入到feature列表里
2. 目前插件的调试，我现在是直接用json文件测试，发现问题后，进行修改，然后单独编译插件，再测试，一直准备针对每个插件写测试用例的，但这个编码工作有点大，估计需要一定的时间。

**Comment by weihebu** [comment]
感谢解答
1.请问如何单独编译插件，能告知下命令吗？
2.阿里那边的源码编译后为tar.gz包，这边是否也可以办到呢？

**Comment by wgzhao** [comment]
>1.请问如何单独编译插件，能告知下命令吗？
如果实在一些IDE开发工具上，可以直接选择模块进行编译即可  
如果是在命令行编译，则可以使用 `mvn package -pl: <module name> -am` 进行编译

>2.阿里那边的源码编译后为tar.gz包，这边是否也可以办到呢？
这个原来是目录及压缩包都有，但是因为占用磁盘空间很大，所以我删除了，可以考虑加上

**Comment by wgzhao** [comment]
@weihebu 新增了Oracle 及 PostgreSQL 的更新插入功能，你可以测试。
