### ISSUE TITLE
添加org.glassfish:javax.el:pom:3.0.1-b06-SNAPSHOT依赖报错

### ISSUE THREAD

**Issue by weihebu** [wgzhao/DataX#88]
感谢更新，下午我拿来测试下。
1.项目处理org.glassfish:javax.el:pom:3.0.1-b06-SNAPSHOT依赖报错，错误信息如下：
  Could not find artifact org.glassfish:javax.el:pom:3.0.1-b06-SNAPSHOT in apache release 
  (https://repository.apache.org/content/repositories/releases/)
查了下项目里现在应该依赖3.0.1-b12版本，这个错误不影响编译打包。
2.希望更新下mysql的驱动，同时更新下驱动 MySql("mysql", "com.mysql.cj.jdbc.Driver")。

**Comment by wgzhao** [comment]
感谢反馈

>1.项目处理org.glassfish:javax.el:pom:3.0.1-b06-SNAPSHOT依赖报错

那个模块报出来的？我本地没有，麻烦贴下完整报错信息

>2.希望更新下mysql的驱动，同时更新下驱动 MySql("mysql", "com.mysql.cj.jdbc.Driver")。

这个没有更新完全是因为我目前生产环境有一套古老的MySQL 服务，古老到新的驱动版本不兼容，所以之前更新过后发现出了问题，然后再降级下来的，我看怎么处理这个兼容性问题。

**Comment by weihebu** [comment]
![依赖报错](https://user-images.githubusercontent.com/23256526/103118636-c812ec00-46aa-11eb-8d69-ee52295429d0.jpg)
这个问题只有在项目刚下过来第一次处理依赖的时候会报，当我点击  reload all maven projects后又会恢复正常。我在各个插件的pom里搜索过也没找到这个依赖，感觉上只要去掉就行了，但是就是不知道在哪。

**Comment by weihebu** [comment]
另外不知道你用不用datax-web，datax-web在生成oracle模板时字段形式为"/"id/""。结合datax采用update(id)的形式，会导致sql模板拼接错误。

**Comment by wgzhao** [comment]
> 1. 另外不知道你用不用datax-web

datax-web 的使用流程不太适合我目前的方式，我们实际上使用了一种更为有效的办法，不过是多种工具结合而成，还不是一个完整的系统。
你说的这个问题，可以去 datax-web项目提issue看看是不是可以从那里直接解决

>2.此外我还在项目中看到没有被添加的模块：hbase20xreader

这个模块还有些问题，我还在开发中

**Comment by weihebu** [comment]
ok，感谢解答。

**Comment by weihebu** [comment]
![javaxel错误](https://user-images.githubusercontent.com/23256526/103126027-f7842180-46c7-11eb-8efc-48cdb2eec843.jpg)
你好，编译的时候也能看到关于这个jar包的警告。

**Comment by wgzhao** [comment]
我本地清理所有缓存再编译也无法重现你出现的这个问题，放到github上也没有重现，你尝试手工执行 

```shell
mvn clean package -pl :hbase20xsqlreader
```

看是否有这个警告信息

**Comment by weihebu** [comment]
![错误](https://user-images.githubusercontent.com/23256526/103131092-4e92f200-46da-11eb-8e54-053892ea1225.jpg)
1.警告依旧。
2.其实上次请教了那个命令后，我编译没有成功过，报错如图。后来我用 mvn -U -pl hbase20xsqlreader -am clean package 这个命令可以构建。

**Comment by weihebu** [comment]
![缺jar包](https://user-images.githubusercontent.com/23256526/103134273-0c25e100-46eb-11eb-96f4-08d27c71c001.jpg)
![QQ截图20201225194740](https://user-images.githubusercontent.com/23256526/103134276-0d570e00-46eb-11eb-918a-e3aa8854d4cb.jpg)
家里的台式机也是一样的问题，但是重新点击maven reload，又是绿色通过的。

**Comment by wgzhao** [comment]
@weihebu  实际上，我只认可命令行下执行maven命令的报错，IDE工具编译时提交了太多的参数。你试下在命令行手工编译试下。
我这里的确无法再现你出现的问题

**Comment by weihebu** [comment]
我用idea的插件maven helper查了下，会不会是hbase20xsqlreader依赖的javax.servlet.jsp造成的，因为它的pom文件第291行版本申明跟平时的写法不一样。
 <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>javax.el</artifactId>
            <version>[3.0.0,)</version>
</dependency>
这表示依赖3.0往上最新版本的意思？
依赖关系如图所示
![依赖](https://user-images.githubusercontent.com/23256526/103622483-c5997780-4f71-11eb-9925-758c183d22a6.jpg)

**Comment by weihebu** [comment]
可以确定确实是hbase20xsqlreader这个模块编译时候会报上述警告，我删除了其他插件编译，确实就是它出的。

**Comment by wgzhao** [comment]
1. `[x,y)` 这种写法是表示一个支持某一个范围的版本
2. 你看下 `master` 上的 [pom.xml](https://raw.githubusercontent.com/wgzhao/DataX/master/hbase20xreader/pom.xml) 文件，和你的不一样，你拉取下最新代码试试

**Comment by weihebu** [comment]
你好，我这边把hbase20xsqlreader模块的pom文件中的phoenix-core排除：
![aaa](https://user-images.githubusercontent.com/23256526/103719469-0c37b200-5004-11eb-8e40-276b5e6d9c3d.jpg)
就没有这些警告了。
你那边没有复现，我这边也只是警告，就记录下吧。昨天我下过最新的，我本地环境依旧会报这个错误，但也就报一次，后面就是四个警告。
