### ISSUE TITLE
dbffilewriter插件功能是不是还没做完

### ISSUE THREAD

**Issue by haiying1991** [wgzhao/DataX#9]
你好，dbffilewriter插件功能是不是还没做完，发现通过该插件写入生成的dbf文件打不开

**Comment by wgzhao** [comment]
> 你好，dbffilewriter插件功能是不是还没做完，发现通过该插件写入生成的dbf文件打不开

嗯，还存在一些问题，正在修改，感谢反馈

**Comment by wgzhao** [comment]
已经修复，具体使用可以参考文档 [dbfilewriter.md](https://github.com/wgzhao/DataX/blob/master/docs/dbffilewriter.md)
