### ISSUE TITLE
能否添加对postgresql数组类型的支持

### ISSUE THREAD

**Issue by glxfeng** [wgzhao/DataX#90]
大概思路是read时候转换成字符串，write时候如果该字符串因为没有大括号不符合数组格式，提供相应报错信息。
个人编码能力有限，只能提供建议，sql的操作如下
CREATE table test_array(a int,b int[],c varchar[]);
insert into test_array VALUES(1,'{1,2}','{a,b,c}');

另外HashData公司维护的datax很好的实现了对greenplum数据库的读写支持，可以考虑借鉴一下，扩充这个项目支持的数据库类型
https://github.com/HashDataInc/DataX

**Comment by wgzhao** [comment]
感谢反馈，我学习下

**Comment by wgzhao** [comment]
@glxfeng 已经支持更多的数据类型

**Comment by glxfeng** [comment]
@wgzhao 感谢更新
