### ISSUE TITLE
oracle使用update报类型转换错误

### ISSUE THREAD

**Issue by weihebu** [wgzhao/DataX#92]
oracle以及postgresql的update模式，我测试过了。其中oracle使用update报类型转换错误，经查发现CommonRdbmsWriter类中i=0会导致resultSetMetaData变量字段顺序错误。我提交了代码，你可以看下。另外我想请教下，每次任务运行成功后，软件都会弹出一个地址，但随即又报失败，请问你遇到过吗？
![请教](https://user-images.githubusercontent.com/23256526/103518405-af76b300-4eae-11eb-8a3f-1be826434e3f.jpg)

**Comment by wgzhao** [comment]
感谢反馈
1. 麻烦提供你的Oracle 测试job文件以及对应的Oracle建表语句，我尝试在本地重现
2. 连接 `127.0.0.1:7001`的问题，你看下 `conf/core.json` 文件里的 `core.dataXServer.address` 是否配置了地址，如果没有，看是否有代理配置之类的环境变量信息。

**Comment by weihebu** [comment]
{
  "job": {
    "setting": {
      "speed": {
        "channel": 3
      },
      "errorLimit": {
        "record": 0,
        "percentage": 0.02
      }
    },
    "content": [
      {
        "reader": {
          "name": "oraclereader",
          "parameter": {
            "username": "***",
            "password": "***",
            "column": [
              "\"id\"",
              "\"name\"",
              "\"update_date\"",
              "\"remark\""
            ],
            "connection": [
              {
                "table": [
                  "\"student\""
                ],
                "jdbcUrl": [
                  "jdbc:oracle:thin:@//****:1521/orcl"
                ]
              }
            ]
          }
        },
        "writer": {
          "name": "oraclewriter",
          "parameter": {
            "username": "***",
            "password": "***",
            "column": [
              "\"id\"",
              "\"name\"",
              "\"update_date\"",
              "\"remark\""
            ],
            "writeMode": "update(\"id\")",
            "connection": [
              {
                "table": [
                  "\"student1\""
                ],
                "jdbcUrl": "jdbc:oracle:thin:@//****:1521/orcl"
              }
            ]
          }
        }
      }
    ]
  }
}

**Comment by weihebu** [comment]
我这个job是用dataxweb生成的，所以看起来有些奇怪。
create table STUDENT
(
  ID          VARCHAR2(10),
  NAME        VARCHAR2(30),
  UPDATE_TIME DATE,
  REMARK      VARCHAR2(50)
)

wgzhao <notifications@github.com> 于2021年1月4日周一 下午5:14写道：

**Comment by weihebu** [comment]
你好，建表语句已发送至谷歌邮箱，另外附件为job文件。

**Comment by weihebu** [comment]
请教下以下两个问题：
1，postgresqlwriter的"writeMode": "update(col1, col2...)"模式，会报出ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification，不像oracle随意些。
2，打包命令，应该可以组合成一条：mvn clean package -DskipTests assembly:single，我这边可以打包成功。

**Comment by wgzhao** [comment]
> 请教下以下两个问题：
> 1，postgresqlwriter的"writeMode": "update(col1, col2...)"模式，会报出ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification，不像oracle随意些。
> 2，打包命令，是否可以组合成一条命令：mvn clean package -DskipTests assembly:single？项目刚下载的时候用这个命令打包不成功，但是用mvn clean package,mvn package assembly:single这两条命令打包一次后，再用mvn clean package -DskipTests assembly:single 可以打包成功，有点奇怪。。。

1. PostgreSQL `insert into ... on conflict` 要求字段或联合字段必须是具有唯一性，详细可以参考[官方文档](https://www.postgresql.org/docs/9.5/sql-insert.html#SQL-ON-CONFLICT)
2. 打包这个问题一直存在，所以README里说的是分两次执行，也尝试了很多办法，但在目前pom,package文件的层级机构下，我还没有搞定。
