### ISSUE TITLE
插件补充

### ISSUE THREAD

**Issue by cmdares** [wgzhao/DataX#96]
希望平台能够集成更多的数据源。提供一些参考建议，希望能够把这个项目做成集大成一体。
Datax支持Redis Writer
https://blog.csdn.net/u013289115/article/details/106277937

Datax支持Kudu Writer
https://github.com/amygbj/kuduwriter

Datax支持Kudu Reader
alibaba/DataX#538

GpdbWriter 使用copy from方式写入
https://github.com/HashDataInc/DataX/tree/master/gpdbwriter

InfluxDBReader
https://github.com/wowiscrazy/InfluxDBReader-DataX

InfluxDBWriter？？？尚未找到实现（物联网有前景数据库，希望能够实现）

**Comment by wgzhao** [comment]
感谢你的反馈

1. Redis的读写插件已经实现，README里只是没有体现，我等下加上
2. 其他数据库的支持，我正在探索，有些数据库我自己没有使用过，还需要先熟悉。

**Comment by cmdares** [comment]
@wgzhao 👍

**Comment by WeiLinCool** [comment]
大佬能否开发个插件支持HttpReader，从Http中读取数据，然后存储到数据库中

**Comment by WeiLinCool** [comment]
> 大佬能否开发个插件支持HttpReader，从Http中读取数据，然后存储到数据库中

https://github.com/zhzava/DOC/wiki/datax-httpheader%E6%8F%92%E4%BB%B6%E4%BB%8B%E7%BB%8D 这个是相关功能的wiki

**Comment by cmdares** [comment]
@WeiLinCool  这个需求提的好，以往项目中基本都是使用kettle在完成，若datax能够整合进去就完美了。注意，这里需要针对Json等返回数据进行解析，看看如何才能通过注入响应的转换器，将数据提取出格式化。同时需要注意，服务的接缓存问题，提高并发连续抽取的稳定性。

**Comment by wgzhao** [comment]
上述提及的插件均已实现
