### ISSUE TITLE
期望添加httpReader插件功能

### ISSUE THREAD

**Issue by WeiLinCool** [wgzhao/DataX#98]
开发httpReader 插件：
功能：从Http 中读取数据，写入到数据库
相关WIKI：https://github.com/zhzava/DOC/wiki/datax-httpheader%E6%8F%92%E4%BB%B6%E4%BB%8B%E7%BB%8D

**Comment by weihebu** [comment]
这个功能还是挺实用的。

**Comment by dongjunchuan** [comment]
@weihebu @wgzhao 目前addax里httpreader暂不支持分页。比如数据提供方提供了一个totalSize几千万行的分页查询接口，要把这几千万行同步到mysql，在httpreader里支持分页是否可行？还是说应该从外部给httpreader多次传参，多次触发该同步任务？
