### ISSUE TITLE
看到这个版本的datax支持oracle的merge into功能，但是放在datax  web上就不能用了

### ISSUE THREAD

**Issue by czxin788** [wgzhao/DataX#99]
看到这个版本的datax支持oracle的merge into功能，但是放在datax  web上就不能用了。
https://github.com/WeiYe-Jing/datax-web/blob/master/doc/datax-web/datax-web-deploy.md

**Comment by weihebu** [comment]
可以用，因为模板生成的字段是带有转义字符，所以导致源码中进行字段匹配的时候匹配不上，你参考下我的写法。或者你可以删除转义字符，也是可以使用的。
![image](https://user-images.githubusercontent.com/23256526/104197289-c9406900-545f-11eb-8679-4de67fb90e3d.png)

**Comment by weihebu** [comment]
@wgzhao 这个事情可不可以加入文档说明下？dataxweb用的人蛮多的，不说明下，后面应该还会有人问。

**Comment by wgzhao** [comment]
> @wgzhao 这个事情可不可以加入文档说明下？dataxweb用的人蛮多的，不说明下后面应该还会有人问。

好的，不过我没用过datax-web，你能给个例子或操作说明吗？

**Comment by weihebu** [comment]
操作说明：https://github.com/WeiYe-Jing/datax-web
postgresql生成的json模板如下图。
![image](https://user-images.githubusercontent.com/23256526/104200252-6355e080-5463-11eb-86bc-13ab4167eb84.png)
1：如果想要实现update模式，参数需要自己手工添加。要么去掉比如说id的转义字符，要么连带着转义字符写到update的参数里。
2：模板中还有个小问题，就是自动生成限速的byte参数。这个参数不能只配置一个，配了这个则还需要配置一个全局的限速，它这边却没有生成。这个byte参数搭配阿里的软件包却没有报错，但是我本地调试阿里源码时会报错。你开发的版本，部署以及调试，用这个模板是都会报错的。当然配置不对，软件报错才是对的。当然也可以粗暴地删除它来解决问题。

**Comment by weihebu** [comment]
https://zhmin.github.io/2018/12/16/datax-ratelimiter-bug/
不报错的原因找到，可以参考此文章。我查了下阿里以及你修改的源码，这边已经正确throw这个错误了。
